// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: battery_monitor

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_StatusBar;
extern lv_obj_t *ui_TempContainer;
extern lv_obj_t *ui_Label_Temperature;
extern lv_obj_t *ui_Label15;
extern lv_obj_t *ui_Clock;
extern lv_obj_t *ui_ClockLabel;
extern lv_obj_t *ui_BatOuter;
extern lv_obj_t *ui_ScreenMain_Bat;
extern lv_obj_t *ui_Battery;
extern lv_obj_t *ui_ScreenMain_ContainerBatt;
extern lv_obj_t *ui_ScreenMain_Charging;
extern lv_obj_t *ui_ScreenMain_Label3;
extern lv_obj_t *ui_ScreenMain_Label4;
extern lv_obj_t *ui_Container1;
extern void ui_event_Container_Voltage( lv_event_t * e);
extern lv_obj_t *ui_Container_Voltage;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_Label_Capacity;
extern lv_obj_t *ui_Label5;
extern void ui_event_Container_Capacity( lv_event_t * e);
extern lv_obj_t *ui_Container_Capacity;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_Label_Max_current;
extern lv_obj_t *ui_Label7;
extern void ui_event_Container_Power( lv_event_t * e);
extern lv_obj_t *ui_Container_Power;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Label_Max_Power;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Container2;
extern void ui_event_Container_Voltage1( lv_event_t * e);
extern lv_obj_t *ui_Container_Voltage1;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_Label_Voltage;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_Label_Max_Voltage;
extern lv_obj_t *ui_Label_Max_Voltage1;
extern lv_obj_t *ui_Container_Capacity1;
extern lv_obj_t *ui_Label10;
extern lv_obj_t *ui_Label_Current;
extern lv_obj_t *ui_Label11;
extern lv_obj_t *ui_Container_Power1;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Label_Power;
extern lv_obj_t *ui_Label13;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

