// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: battery_monitor

#ifndef UI_SCREEN_RPM_H
#define UI_SCREEN_RPM_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_screen_RPM
extern void ui_screen_RPM_screen_init(void);
extern void ui_screen_RPM_screen_destroy(void);
extern lv_obj_t *ui_screen_RPM;
extern lv_obj_t *ui_Arc1;
extern lv_obj_t *ui_LabelRPM;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Label16;
extern lv_obj_t *ui_Label17;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

