// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 9.1.0
// Project name: battery_monitor

#include "../ui.h"

lv_obj_t *ui_screen_RPM;
lv_obj_t *ui_Arc1;
lv_obj_t *ui_LabelRPM;
lv_obj_t *ui_Label14;
lv_obj_t *ui_Label16;
lv_obj_t *ui_Label17;

// event funtions

// build funtions

void ui_screen_RPM_screen_init(void)
{
ui_screen_RPM = lv_obj_create(NULL);
lv_obj_remove_flag( ui_screen_RPM, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_screen_RPM, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_screen_RPM, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Arc1 = lv_arc_create(ui_screen_RPM);
lv_obj_set_width( ui_Arc1, 200);
lv_obj_set_height( ui_Arc1, 200);
lv_obj_set_align( ui_Arc1, LV_ALIGN_CENTER );
lv_arc_set_range(ui_Arc1, 0,2000);
lv_arc_set_value(ui_Arc1, 0);
lv_obj_set_style_arc_color(ui_Arc1, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelRPM = lv_label_create(ui_screen_RPM);
lv_obj_set_width( ui_LabelRPM, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelRPM, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelRPM, 1 );
lv_obj_set_y( ui_LabelRPM, -11 );
lv_obj_set_align( ui_LabelRPM, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelRPM,"text");
lv_obj_set_style_text_color(ui_LabelRPM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelRPM, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelRPM, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label14 = lv_label_create(ui_screen_RPM);
lv_obj_set_width( ui_Label14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label14, -2 );
lv_obj_set_y( ui_Label14, 34 );
lv_obj_set_align( ui_Label14, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label14,"RPM");
lv_obj_set_style_text_color(ui_Label14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label14, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label16 = lv_label_create(ui_screen_RPM);
lv_obj_set_width( ui_Label16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label16, 110 );
lv_obj_set_y( ui_Label16, 70 );
lv_obj_set_align( ui_Label16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label16,"2000");
lv_obj_set_style_text_color(ui_Label16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label17 = lv_label_create(ui_screen_RPM);
lv_obj_set_width( ui_Label17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label17, 0 );
lv_obj_set_y( ui_Label17, -111 );
lv_obj_set_align( ui_Label17, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label17,"1000");
lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_screen_RPM_screen_destroy(void)
{
   if (ui_screen_RPM) lv_obj_del(ui_screen_RPM);

// NULL screen variables
ui_screen_RPM= NULL;
ui_Arc1= NULL;
ui_LabelRPM= NULL;
ui_Label14= NULL;
ui_Label16= NULL;
ui_Label17= NULL;

}
