// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.1.0
// Project name: battery_monitor

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t *ui_Screen1;
lv_obj_t *ui_Label1;
lv_obj_t *ui_StatusBar;
lv_obj_t *ui_Clock;
lv_obj_t *ui_ClockLabel;
lv_obj_t *ui_BatOuter;
lv_obj_t *ui_ScreenMain_Bat;
lv_obj_t *ui_Battery;
lv_obj_t *ui_ScreenMain_ContainerBatt;
lv_obj_t *ui_ScreenMain_Charging;
lv_obj_t *ui_ScreenMain_Label3;
lv_obj_t *ui_ScreenMain_Label4;
lv_obj_t *ui_Container1;
lv_obj_t *ui_Container_Voltage;
lv_obj_t *ui_Label4;
lv_obj_t *ui_Label_Voltage;
lv_obj_t *ui_Label5;
void ui_event_Container_Capacity( lv_event_t * e);
lv_obj_t *ui_Container_Capacity;
lv_obj_t *ui_Label6;
lv_obj_t *ui_Label_Capacity;
lv_obj_t *ui_Label7;
lv_obj_t *ui_Container_Power;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Label_Power;
lv_obj_t *ui_Label2;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Container_Capacity( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      CapacityClicked( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_display_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Screen1_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Screen1);
}
